import pygal
from DieClass import Die
die=Die()
results=[]
for roll_num in range(1000):
    result=die.roll()
    results.append(result)
frequencies=[]
for value in range(1,die.num_sides+1):
    frequency=results.count(value)
    frequencies.append(frequency)
hist=pygal.Bar()
hist.title="Results of rolling one D6 1000 times"
hist.x_labels=['1','2','3','4','5','6']
hist._x_title="Result"
hist.y_title="Frequency of Result"
hist.add('D6',frequencies)                        #That element is the chart legend, which is automatically generated by the pygal data visualization library.
hist.render_to_file('die_visual.svg')             #It appears on your graph because of Line 17 in your code:


##How it breaks down:
# The Text (D6): Whatever string you pass as the first argument inside the hist.add() function serves as the label for that specific data series.
# The Red Square: pygal assigns a distinct color to each dataset added to the chart so you can tell them apart. Since it is the first dataset added, it chose red to match the color of your histogram bars.